### ISSUE TITLE
Doesn't detect unused export in .d.ts file

### ISSUE THREAD

**Issue by emlai** [pzavolinsky/ts-unused-exports#59] opened 2019-10-28 12:36 UTC
Using ts-unused-exports version 3.0.0.

Invocation: `ts-unused-exports ./tsconfig.json --showLineNumber --exitWithCount`

tsconfig.json:

```json

{
  "compilerOptions": {
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "outDir": "out",
    "sourceMap": true,
    "strictNullChecks": true,
    "strictBindCallApply": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": false,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "target": "es6",
    "module": "commonjs",
    "lib": [
      "dom",
      "es2017"
    ]
  },
  "include": [
    "backend",
    "client",
    "common",
    "migrations",
    "scripts",
    "test",
    "types"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

The .d.ts file in question is located under `types/`, and it is being imported from other project files.

**Comment by mrseanryan** [comment] 2019-10-29 08:05
Currently the parser skips d.ts files.

I think they could be used in a library project, in which case they are intended for consumption by client, and so unused exports are not (definitely) a problem. 

@pzavolinsky is that why the code is skipping `d.ts` files?

**Comment by emlai** [comment] 2019-10-29 09:32
We are using .d.ts files in an application project, so the unused exports are as much a problem as in any other file.

I just tried renaming the file from `.d.ts` to `.ts` and now the unused exports are being reported correctly. Still, would be nice to not have to rename them, as we have a lot of them.

If using ts-unused-exports in a library project, unused exports in .ts files might be intended for external consumption as well, so they would need to be marked with `// ts-unused-exports:disable-next-line` anyway. Could the same usage be used also for .d.ts files, instead of skipping them?

**Comment by mrseanryan** [comment] 2019-10-29 16:56
What about adding an option for this? 

- -IncludeAmbientFiles

(since it could raise more warnings for existing users, who might not want that)

**Comment by pzavolinsky** [comment] 2019-10-29 19:31
@mrseanryan the option works for me.

I agree that some people might not really care about unused symbols in declaration files, but on the other hand @emlai makes a good case for this scenario being supported (even if it's behind an option).

We should add a regression test for this scenario.

**Comment by mrseanryan** [comment] 2019-11-02 17:22
note: when addressing this, it could be good to also test for #29

**Comment by emlai** [comment] 2019-11-02 21:17
Might be better to include declaration files by default, and have a `--excludeDeclarationFiles` option?

Because otherwise new users who don't know about the flag might think their .d.ts files are being checked, but actually they aren't. Requiring the user to explicitly opt out of checking .d.ts files avoids this footgun.

**Comment by mrseanryan** [comment] 2019-11-03 04:22
Sounds reasonable - @pzavolinsky what do you think?

**Comment by pzavolinsky** [comment] 2019-11-04 02:21
Fine by me, we'll bump the major to signal this is a "breaking" change. We can add docs in the README/CHANGELOG to let people know of the flag to disable this behavior.

**Comment by mrseanryan** [comment] 2019-11-23 06:26
@emlai - Thank you for raising this issue. 

We've released version 5 which support d files. 

(Closing) 
Sean

**Closed by mrseanryan** 2019-11-23 06:26 UTC
