### ISSUE TITLE
False positive with path aliases and sub-folders

### ISSUE THREAD

**Issue by ilyin371** [pzavolinsky/ts-unused-exports#154] opened 2020-07-22 12:16 UTC
Steps to reproduce with `example\with-paths`:

1. Move `utils\src\calculations.ts` into a new sub-folder `utils\src\sub\calculations.ts`.
2. Update import statement in `math.ts` to `import {calculations} from 'utils/sub/calculations';`
3. Run `ts-unused-exports example\with-paths\tsconfig.json`
4. `utils\src\sub\calculations.ts: calculations` is falsely reported as unused.

**Comment by mrseanryan** [comment] 2020-07-22 18:09
Thank you for reporting it

**Comment by mrseanryan** [comment] 2020-10-11 17:46
hi @ilyin371  - I cannot repro this issue.

I pushed a branch where I try the above, but it seems to work OK for me!

branch = `scratch/path-alias-issue-154`

```
cd example/with-paths
node ../../bin/ts-unused-exports tsconfig.json
```

OUTPUT:

```
.../example/with-paths/math.ts: add1
```

(calculations.ts does NOT appear as unused)

**Comment by mrseanryan** [comment] 2020-10-11 17:50
@ilyin371 is there something about your `tsconfig.json` file ?  :thinking:

**Comment by mrseanryan** [comment] 2020-10-11 18:01
My `tsconfig.json` is:

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es5",
    "noEmit": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "paths": {
      "utils": ["utils/src"],
      "utils/*": ["utils/src/*"]
    }
  }
}
```

**Comment by kevinoliveira** [comment] 2020-10-23 19:03
same issue here, I can confirm it's due to path aliases. i can create a reproducible environment later today.

**PS:** awesome project

**Comment by mrseanryan** [comment] 2020-10-24 10:39
@kevinoliveira if you can post example or even better make a fork with working example, that would be great!

**Comment by kevinoliveira** [comment] 2020-10-26 02:10
@mrseanryan i hope this can be useful
https://github.com/kevinoliveira/ts-unused-exports-issue-154-example

**Comment by mrseanryan** [comment] 2020-10-26 19:02
cheers @kevinoliveira 

I think it is related to the `#customAlias` part:

```
import { sayHelloWorldInJapanese } from "#customAlias/helpers";
```

This helps a lot!

**Comment by mrseanryan** [comment] 2020-11-08 16:51
@ilyin371 @kevinoliveira  have a fix here:

https://github.com/pzavolinsky/ts-unused-exports/pull/176

If you have the time, it would great to get feedback before we merge and release.

Branch is:

fix/path-aliases-and-sub-folders

**Comment by mrseanryan** [comment] 2020-11-11 20:50
fixed in 7.0.0

**Comment by kevinoliveira** [comment] 2020-11-12 13:37
@mrseanryan sorry for the delay, there is no more false positives.

**Comment by aryzing** [comment] 2023-01-26 12:31
@mrseanryan has it been resolved? I seem to be having the same issue with the latest version.

In the repro below, there's a single export `foo` being reported as unused, despite it clearly being used,
https://github.com/aryzing/practice-ts-unused-exports

**Comment by aryzing** [comment] 2023-01-26 13:23
Seems to be related to the fact that the file imported is the index file. I've noticed that in the past there have been several issues related to index-related false positives, so may be a regression?

- https://github.com/pzavolinsky/ts-unused-exports/issues/220
- https://github.com/pzavolinsky/ts-unused-exports/issues/222

**Comment by mrseanryan** [comment] 2023-01-29 11:21
@aryzing  thanks for reporting.
This is about the `@` part of the import which is not something supported.

import { foo } from "`@`foo/index";

Opening as a new issue ...

**Closed** 2023-01-29 11:23 UTC
Labels: bug, help wanted

**Comment by mrseanryan** [comment] 2023-01-29 12:32
UPDATE:

Ineed, the problem is the file being imported is index
Another very similar file other works OK.

but at this point its simpler for me to manage, as a separate related issue.
