### ISSUE TITLE
Add as es-lint rule

### ISSUE THREAD

**Issue by aspirisen** [pzavolinsky/ts-unused-exports#82] opened 2019-11-06 11:29 UTC
It would be very good if we would have this tool as es-lint rule, so we could have alerts inside our IDE.

**Comment by mrseanryan** [comment] 2019-11-07 07:05
It would be nice @aspirisen ! - 

There is already a similar issue https://github.com/pzavolinsky/ts-unused-exports/issues/19

Do you mind if we close this one?

**Comment by aspirisen** [comment] 2019-11-07 09:10
Ok, thanks

**Comment by mrseanryan** [comment] 2019-11-07 10:32
Duplicate of #19

**Closed** 2019-11-07 10:32 UTC
